### ISSUE TITLE
Support for server-icon

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [andrewrk/node-minecraft-protocol#109]

**Comment by GeoffreyFrogeye** [comment]
My bad, already implemented. GitHub search didn't gave any result for "favicon" while searching for "icon".

**Comment by vincss** [comment]
I can't get the favicon option to work. Can you tell me how did you do ?
I've created a 64x64 png converted to a data64 via an online converter http://www.askapache.com/online-tools/base64-image-converter/
But it doesn't display the image.

**Comment by rom1504** [comment]
you need to pass it through https://github.com/PrismarineJS/node-minecraft-protocol/tree/master/doc#mccreateserveroptions beforePing https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createServer.js#L105

**Comment by vincss** [comment]
Thanks it's working like this ! 
		beforePing : function(reponse, client) {
			reponse.favicon = faviconString;
		}
var faviconString = "data:image/png;base64, ...."
